language: cpp
compiler:
- gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl-* libglm-dev libboost-all-dev

branches:
  only:
    - master

notifications:
  email: true

os:
- linux
- osx
- windows

sudo: true

env:
- PYTHONPATH =/home/MLaker/Projects/Year2Sem2/GameDev/ProjTest/GameDevYearTwoAssigmentOne/src/.libs ../pyhydra.py

