language: cpp
compiler:
- gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-* libglm-dev libboost-all-dev libglew-dev  -y
  - autoreconf -i

branches:
  only:
    - master

notifications:
  email: true

os:
- linux
- osx

sudo: true
