language: cpp
compiler:
- gcc

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libsdl-* libglm-dev libboost-all-dev boost-* glew-devel SDL2_* glm-devel -y
  - autoreconf -i

branches:
  only:
    - master

notifications:
  email: true

os:
- linux
- osx

sudo: true

env:
- PYTHONPATH =/home/MLaker/Projects/Year2Sem2/GameDev/ProjTest/GameDevYearTwoAssigmentOne/src/.libs ../pyhydra.py

